# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the application
RUN npm run build

# Set executable permission for run.sh
RUN chmod +x ./run.sh

# Expose the application via an entry point. The run.sh requires a keypair argument, which is passed via command-line args.
ENTRYPOINT ["sh", "./run.sh"]

# Default command for local testing. This will fail without a keypair argument, so it's expected to be overridden.
CMD ["./example-keypair.json"]
